create table if not exists OWNERS(
	USER_ID INTEGER NOT NULL,
	ALBUM_ID INTEGER NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
	FOREIGN KEY(ALBUM_ID) REFERENCES ALBUMS(ID) ON DELETE CASCADE
);
