create table if not exists HISTORY(
	WALLET_ID INTEGER NOT NULL,
	ALBUM_ID INTEGER NOT NULL,
	DATE TXT DEFAULT UNKNOWN,
	FOREIGN KEY(WALLET_ID) REFERENCES WALLET(ID),
	FOREIGN KEY(ALBUM_ID) REFERENCES ALBUMS(ID)
);	
